name: flutter_rename_app_plus
description: A package that enable to rename an entire app and ids in one command.
version: 1.2.0
homepage: https://github.com/flutter-fast-kit/flutter_rename_app_plus

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  yaml: ^3.1.2
  process_run: ^0.13.0
  ansicolor: ^2.0.1
